### ISSUE TITLE
CI/CD Patterns and Improve Code Organization

### ISSUE THREAD

**Issue by cokacho** [dougc95/saas-report-wmm#7]
# Add Basic CI/CD Pipeline

## Description
Implement a basic CI/CD pipeline using GitHub Actions to automate testing, linting, and deployment processes.

## Tasks
- [ ] Add GitHub Actions workflow for:
  - [ ] Frontend: Build, test, lint
  - [ ] Backend: Test, lint
  - [ ] Docker image building
  - [ ] Automated deployment to Vercel

## Implementation
Create `.github/workflows/ci.yml`:
```yaml
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: cd apps/frontend && npm ci
      - run: npm run test
      - run: npm run build

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: cd apps/backend && pip install -r requirements.txt
      - run: pytest
```

## References
- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [Vercel GitHub Integration](https://vercel.com/docs/git-integrations/vercel-for-github)
- [Docker Build Action](https://github.com/docker/build-push-action)

## Acceptance Criteria
- [ ] Pipeline runs on push to main and PRs
- [ ] All tests pass
- [ ] No linting errors
- [ ] Successful build
- [ ] Automated deployment to Vercel
